import { Function, FunctionRuntime, SourceCodeType } from '../models';
import { FunctionLanguage } from '../models/function-language';
import { FunctionStatus } from '../models/FunctionStatus';

export const mockFunctionsData: Function[] = [
    {
        name: 'test.js',
        description: 'Test',
        runtime: FunctionRuntime.NodeJS,
        sourceCode: {
            language: FunctionLanguage.Javascript,
            type: SourceCodeType.File,
            content: '// Test js',
        },
        status: FunctionStatus.Draft,
        timeout: 30,
        triggers: [],
        initialCode: '// Test js',
        etag: "1",
    },
    {
        name: 'test.ts',
        description: 'Test',
        runtime: FunctionRuntime.NodeJS,
        sourceCode: {
            language: FunctionLanguage.Typescript,
            type: SourceCodeType.File,
            content: '// Test ts',
        },
        status: FunctionStatus.Draft,
        timeout: 30,
        triggers: [],
        initialCode: '// Test ts',
        etag: "1",
    },
    {
        name: 'test.go',
        description: 'Test',
        runtime: FunctionRuntime.Go,
        sourceCode: {
            language: FunctionLanguage.Go,
            type: SourceCodeType.File,
            content: '// Test go',
        },
        status: FunctionStatus.Draft,
        timeout: 30,
        triggers: [],
        initialCode: '// Test go',
        etag: "1",
    },
    {
        name: 'test.java',
        description: 'Test',
        runtime: FunctionRuntime.Java,
        sourceCode: {
            language: FunctionLanguage.Java,
            type: SourceCodeType.File,
            content: '// Test java',
        },
        status: FunctionStatus.Draft,
        timeout: 30,
        triggers: [],
        initialCode: '// Test java',
        etag: "1",
    },
    {
        name: 'test2.js',
        description: 'Test',
        runtime: FunctionRuntime.NodeJS,
        sourceCode: {
            language: FunctionLanguage.Javascript,
            type: SourceCodeType.File,
            content: '// Test 2 js',
        },
        status: FunctionStatus.Draft,
        timeout: 30,
        triggers: [],
        initialCode: '// Test 2 js',
        etag: "1",
    },
    {
        name: 'test2.ts',
        description: 'Test',
        runtime: FunctionRuntime.NodeJS,
        sourceCode: {
            language: FunctionLanguage.Typescript,
            type: SourceCodeType.File,
            content: '// Test 2 ts',
        },
        status: FunctionStatus.Draft,
        timeout: 30,
        triggers: [],
        initialCode: '// Test 2 ts',
        etag: "1",
    },
    {
        name: 'test2.go',
        description: 'Test',
        runtime: FunctionRuntime.Go,
        sourceCode: {
            language: FunctionLanguage.Go,
            type: SourceCodeType.File,
            content: '// Test 2 go',
        },
        status: FunctionStatus.Draft,
        timeout: 30,
        triggers: [],
        initialCode: '// Test 2 go',
        etag: "1",
    },
    {
        name: 'test2.java',
        description: 'Test',
        runtime: FunctionRuntime.Java,
        sourceCode: {
            language: FunctionLanguage.Java,
            type: SourceCodeType.File,
            content: '// Test 2 java',
        },
        status: FunctionStatus.Draft,
        timeout: 30,
        triggers: [],
        initialCode: '// Test 2 java',
        etag: "1",
    },
    {
        name: 'test3.js',
        description: 'Test',
        runtime: FunctionRuntime.NodeJS,
        sourceCode: {
            language: FunctionLanguage.Javascript,
            type: SourceCodeType.File,
            content: '// Test 3 js',
        },
        status: FunctionStatus.Draft,
        timeout: 30,
        triggers: [],
        initialCode: '// Test 3 js',
        etag: "1",
    },
    {
        name: 'test3.ts',
        description: 'Test',
        runtime: FunctionRuntime.NodeJS,
        sourceCode: {
            language: FunctionLanguage.Typescript,
            type: SourceCodeType.File,
            content: '// Test 3 ts',
        },
        status: FunctionStatus.Draft,
        timeout: 30,
        triggers: [],
        initialCode: '// Test 3 ts',
        etag: "1",
    },
    {
        name: 'test3.go',
        description: 'Test',
        runtime: FunctionRuntime.Go,
        sourceCode: {
            language: FunctionLanguage.Go,
            type: SourceCodeType.File,
            content: '// Test 3 go',
        },
        status: FunctionStatus.Draft,
        timeout: 30,
        triggers: [],
        initialCode: '// Test 3 go',
        etag: "1",
    },
    {
        name: 'test3.java',
        description: 'Test',
        runtime: FunctionRuntime.Java,
        sourceCode: {
            language: FunctionLanguage.Java,
            type: SourceCodeType.File,
            content: '// Test 3 java',
        },
        status: FunctionStatus.Draft,
        timeout: 30,
        triggers: [],
        initialCode: '// Test 3 java',
        etag: "1",
    },
];